// SPDX-License-Identifier: Apache-2.0

//*
// Copyright (c) 2026  Panasonic Automotive Systems, Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/uhmi.proto

package uhmi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UHMIService_StartAll_FullMethodName                  = "/uhmi.UHMIService/StartAll"
	UHMIService_StopAll_FullMethodName                   = "/uhmi.UHMIService/StopAll"
	UHMIService_ReloadConfig_FullMethodName              = "/uhmi.UHMIService/ReloadConfig"
	UHMIService_ListAvailableApps_FullMethodName         = "/uhmi.UHMIService/ListAvailableApps"
	UHMIService_ListRunningApps_FullMethodName           = "/uhmi.UHMIService/ListRunningApps"
	UHMIService_GetAppCommand_FullMethodName             = "/uhmi.UHMIService/GetAppCommand"
	UHMIService_GetAppStatus_FullMethodName              = "/uhmi.UHMIService/GetAppStatus"
	UHMIService_RunAppCommand_FullMethodName             = "/uhmi.UHMIService/RunAppCommand"
	UHMIService_RunApp_FullMethodName                    = "/uhmi.UHMIService/RunApp"
	UHMIService_RunAppAsync_FullMethodName               = "/uhmi.UHMIService/RunAppAsync"
	UHMIService_StopApp_FullMethodName                   = "/uhmi.UHMIService/StopApp"
	UHMIService_LaunchApp_FullMethodName                 = "/uhmi.UHMIService/LaunchApp"
	UHMIService_LaunchApps_FullMethodName                = "/uhmi.UHMIService/LaunchApps"
	UHMIService_MoveWindow_FullMethodName                = "/uhmi.UHMIService/MoveWindow"
	UHMIService_MoveWindows_FullMethodName               = "/uhmi.UHMIService/MoveWindows"
	UHMIService_WidenApp_FullMethodName                  = "/uhmi.UHMIService/WidenApp"
	UHMIService_ListDestinations_FullMethodName          = "/uhmi.UHMIService/ListDestinations"
	UHMIService_CreateAppMirror_FullMethodName           = "/uhmi.UHMIService/CreateAppMirror"
	UHMIService_RemoveAppMirror_FullMethodName           = "/uhmi.UHMIService/RemoveAppMirror"
	UHMIService_ApplySystemLayout_FullMethodName         = "/uhmi.UHMIService/ApplySystemLayout"
	UHMIService_SetApplicationLayout_FullMethodName      = "/uhmi.UHMIService/SetApplicationLayout"
	UHMIService_ReSyncSystemLayout_FullMethodName        = "/uhmi.UHMIService/ReSyncSystemLayout"
	UHMIService_SetLayoutCommand_FullMethodName          = "/uhmi.UHMIService/SetLayoutCommand"
	UHMIService_StartSystemAnimation_FullMethodName      = "/uhmi.UHMIService/StartSystemAnimation"
	UHMIService_StartSystemAnimationAsync_FullMethodName = "/uhmi.UHMIService/StartSystemAnimationAsync"
	UHMIService_WaitAsyncAnimation_FullMethodName        = "/uhmi.UHMIService/WaitAsyncAnimation"
	UHMIService_WaitAllAsyncAnimations_FullMethodName    = "/uhmi.UHMIService/WaitAllAsyncAnimations"
	UHMIService_GetAnimationInfo_FullMethodName          = "/uhmi.UHMIService/GetAnimationInfo"
	UHMIService_ActivateWindow_FullMethodName            = "/uhmi.UHMIService/ActivateWindow"
	UHMIService_DeactivateWindow_FullMethodName          = "/uhmi.UHMIService/DeactivateWindow"
	UHMIService_SetAppPriorityGroup_FullMethodName       = "/uhmi.UHMIService/SetAppPriorityGroup"
	UHMIService_ListPriorityGroups_FullMethodName        = "/uhmi.UHMIService/ListPriorityGroups"
	UHMIService_SubscribeNotifications_FullMethodName    = "/uhmi.UHMIService/SubscribeNotifications"
)

// UHMIServiceClient is the client API for UHMIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UHMIServiceClient interface {
	// ============================================================
	// System orchestration (UHMI)
	//
	//	Whole-system lifecycle, configuration and state.
	//
	// ============================================================
	StartAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	StopAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	ReloadConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	// ============================================================
	// Application lifecycle
	//
	//	Query, launch and stop individual applications.
	//
	// ============================================================
	ListAvailableApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	ListRunningApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	GetAppCommand(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error)
	GetAppStatus(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error)
	RunAppCommand(ctx context.Context, in *AppCommandRequest, opts ...grpc.CallOption) (*Response, error)
	RunApp(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error)
	RunAppAsync(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error)
	StopApp(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error)
	// ============================================================
	// App launch & placement (Layout, unified / JSON-less)
	//
	//	Launch apps and move/widen their windows across displays.
	//
	// ============================================================
	// LaunchApp — unified app launch (app.json or JSON-less) plus layout
	// (destName geometry, or initial_layout.json when destName is empty).
	LaunchApp(ctx context.Context, in *LaunchAppRequest, opts ...grpc.CallOption) (*LaunchAppResponse, error)
	// LaunchApps — launch multiple apps simultaneously (best-effort)
	LaunchApps(ctx context.Context, in *LaunchAppsRequest, opts ...grpc.CallOption) (*LaunchAppsResponse, error)
	// MoveWindow — JSON-less window move using virtual_display_areas
	MoveWindow(ctx context.Context, in *MoveWindowRequest, opts ...grpc.CallOption) (*MoveWindowResponse, error)
	// MoveWindows — move multiple app windows simultaneously
	MoveWindows(ctx context.Context, in *MoveWindowsRequest, opts ...grpc.CallOption) (*MoveWindowsResponse, error)
	// WidenApp — JSON-less app widen across two adjacent virtual displays
	WidenApp(ctx context.Context, in *WidenAppRequest, opts ...grpc.CallOption) (*WidenAppResponse, error)
	// ListDestinations — enumerate all valid dest_name values (all 3 tiers)
	ListDestinations(ctx context.Context, in *ListDestinationsRequest, opts ...grpc.CallOption) (*ListDestinationsResponse, error)
	// ============================================================
	// App mirroring (Layout)
	//
	//	Mirror a running app to another destination and remove it.
	//
	// ============================================================
	// CreateAppMirror — dynamically mirror a running app to another destination
	CreateAppMirror(ctx context.Context, in *CreateAppMirrorRequest, opts ...grpc.CallOption) (*CreateAppMirrorResponse, error)
	// RemoveAppMirror — remove a previously created mirror layer
	RemoveAppMirror(ctx context.Context, in *RemoveAppMirrorRequest, opts ...grpc.CallOption) (*RemoveAppMirrorResponse, error)
	// ============================================================
	// System layout & animation (Layout)
	//
	//	Apply system-wide layouts and run window animations.
	//
	// ============================================================
	ApplySystemLayout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	SetApplicationLayout(ctx context.Context, in *SetApplicationLayoutRequest, opts ...grpc.CallOption) (*Response, error)
	// ReSyncSystemLayout — nudge every worker/compositor to catch up with the
	// master's cached scene without sending any layout change; a compositor
	// that was disconnected and reconnected receives its replay snapshot.
	ReSyncSystemLayout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	SetLayoutCommand(ctx context.Context, in *SetLayoutCommandRequest, opts ...grpc.CallOption) (*Response, error)
	StartSystemAnimation(ctx context.Context, in *StartSystemAnimationRequest, opts ...grpc.CallOption) (*Response, error)
	StartSystemAnimationAsync(ctx context.Context, in *StartSystemAnimationAsyncRequest, opts ...grpc.CallOption) (*Response, error)
	WaitAsyncAnimation(ctx context.Context, in *WaitAsyncAnimationRequest, opts ...grpc.CallOption) (*Response, error)
	WaitAllAsyncAnimations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	GetAnimationInfo(ctx context.Context, in *GetAnimationInfoRequest, opts ...grpc.CallOption) (*GetAnimationInfoResponse, error)
	// ============================================================
	// Window activation & priority groups (Layout)
	// ============================================================
	// ActivateWindow — bring app layers to the front of their priority group
	ActivateWindow(ctx context.Context, in *ActivateWindowRequest, opts ...grpc.CallOption) (*Response, error)
	// DeactivateWindow — send app layers to the back of their priority group and hide them
	DeactivateWindow(ctx context.Context, in *DeactivateWindowRequest, opts ...grpc.CallOption) (*Response, error)
	// SetAppPriorityGroup — permanently reassign all layers of an app to the specified priority group
	SetAppPriorityGroup(ctx context.Context, in *SetAppPriorityGroupRequest, opts ...grpc.CallOption) (*Response, error)
	// ListPriorityGroups — list all priority groups with their current runtime app assignments
	ListPriorityGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListPriorityGroupsResponse, error)
	// ============================================================
	// Notifications (Layout)
	// ============================================================
	SubscribeNotifications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UHMIService_SubscribeNotificationsClient, error)
}

type uHMIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUHMIServiceClient(cc grpc.ClientConnInterface) UHMIServiceClient {
	return &uHMIServiceClient{cc}
}

func (c *uHMIServiceClient) StartAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_StartAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) StopAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_StopAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ReloadConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_ReloadConfig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ListAvailableApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_ListAvailableApps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ListRunningApps(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_ListRunningApps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) GetAppCommand(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_GetAppCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) GetAppStatus(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_GetAppStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) RunAppCommand(ctx context.Context, in *AppCommandRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_RunAppCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) RunApp(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_RunApp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) RunAppAsync(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_RunAppAsync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) StopApp(ctx context.Context, in *AppControlRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_StopApp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) LaunchApp(ctx context.Context, in *LaunchAppRequest, opts ...grpc.CallOption) (*LaunchAppResponse, error) {
	out := new(LaunchAppResponse)
	err := c.cc.Invoke(ctx, UHMIService_LaunchApp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) LaunchApps(ctx context.Context, in *LaunchAppsRequest, opts ...grpc.CallOption) (*LaunchAppsResponse, error) {
	out := new(LaunchAppsResponse)
	err := c.cc.Invoke(ctx, UHMIService_LaunchApps_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) MoveWindow(ctx context.Context, in *MoveWindowRequest, opts ...grpc.CallOption) (*MoveWindowResponse, error) {
	out := new(MoveWindowResponse)
	err := c.cc.Invoke(ctx, UHMIService_MoveWindow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) MoveWindows(ctx context.Context, in *MoveWindowsRequest, opts ...grpc.CallOption) (*MoveWindowsResponse, error) {
	out := new(MoveWindowsResponse)
	err := c.cc.Invoke(ctx, UHMIService_MoveWindows_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) WidenApp(ctx context.Context, in *WidenAppRequest, opts ...grpc.CallOption) (*WidenAppResponse, error) {
	out := new(WidenAppResponse)
	err := c.cc.Invoke(ctx, UHMIService_WidenApp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ListDestinations(ctx context.Context, in *ListDestinationsRequest, opts ...grpc.CallOption) (*ListDestinationsResponse, error) {
	out := new(ListDestinationsResponse)
	err := c.cc.Invoke(ctx, UHMIService_ListDestinations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) CreateAppMirror(ctx context.Context, in *CreateAppMirrorRequest, opts ...grpc.CallOption) (*CreateAppMirrorResponse, error) {
	out := new(CreateAppMirrorResponse)
	err := c.cc.Invoke(ctx, UHMIService_CreateAppMirror_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) RemoveAppMirror(ctx context.Context, in *RemoveAppMirrorRequest, opts ...grpc.CallOption) (*RemoveAppMirrorResponse, error) {
	out := new(RemoveAppMirrorResponse)
	err := c.cc.Invoke(ctx, UHMIService_RemoveAppMirror_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ApplySystemLayout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_ApplySystemLayout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) SetApplicationLayout(ctx context.Context, in *SetApplicationLayoutRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_SetApplicationLayout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ReSyncSystemLayout(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_ReSyncSystemLayout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) SetLayoutCommand(ctx context.Context, in *SetLayoutCommandRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_SetLayoutCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) StartSystemAnimation(ctx context.Context, in *StartSystemAnimationRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_StartSystemAnimation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) StartSystemAnimationAsync(ctx context.Context, in *StartSystemAnimationAsyncRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_StartSystemAnimationAsync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) WaitAsyncAnimation(ctx context.Context, in *WaitAsyncAnimationRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_WaitAsyncAnimation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) WaitAllAsyncAnimations(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_WaitAllAsyncAnimations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) GetAnimationInfo(ctx context.Context, in *GetAnimationInfoRequest, opts ...grpc.CallOption) (*GetAnimationInfoResponse, error) {
	out := new(GetAnimationInfoResponse)
	err := c.cc.Invoke(ctx, UHMIService_GetAnimationInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ActivateWindow(ctx context.Context, in *ActivateWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_ActivateWindow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) DeactivateWindow(ctx context.Context, in *DeactivateWindowRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_DeactivateWindow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) SetAppPriorityGroup(ctx context.Context, in *SetAppPriorityGroupRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, UHMIService_SetAppPriorityGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) ListPriorityGroups(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListPriorityGroupsResponse, error) {
	out := new(ListPriorityGroupsResponse)
	err := c.cc.Invoke(ctx, UHMIService_ListPriorityGroups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uHMIServiceClient) SubscribeNotifications(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UHMIService_SubscribeNotificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &UHMIService_ServiceDesc.Streams[0], UHMIService_SubscribeNotifications_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &uHMIServiceSubscribeNotificationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UHMIService_SubscribeNotificationsClient interface {
	Recv() (*Notification, error)
	grpc.ClientStream
}

type uHMIServiceSubscribeNotificationsClient struct {
	grpc.ClientStream
}

func (x *uHMIServiceSubscribeNotificationsClient) Recv() (*Notification, error) {
	m := new(Notification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UHMIServiceServer is the server API for UHMIService service.
// All implementations must embed UnimplementedUHMIServiceServer
// for forward compatibility
type UHMIServiceServer interface {
	// ============================================================
	// System orchestration (UHMI)
	//
	//	Whole-system lifecycle, configuration and state.
	//
	// ============================================================
	StartAll(context.Context, *Empty) (*Response, error)
	StopAll(context.Context, *Empty) (*Response, error)
	ReloadConfig(context.Context, *Empty) (*Response, error)
	// ============================================================
	// Application lifecycle
	//
	//	Query, launch and stop individual applications.
	//
	// ============================================================
	ListAvailableApps(context.Context, *Empty) (*Response, error)
	ListRunningApps(context.Context, *Empty) (*Response, error)
	GetAppCommand(context.Context, *AppControlRequest) (*Response, error)
	GetAppStatus(context.Context, *AppControlRequest) (*Response, error)
	RunAppCommand(context.Context, *AppCommandRequest) (*Response, error)
	RunApp(context.Context, *AppControlRequest) (*Response, error)
	RunAppAsync(context.Context, *AppControlRequest) (*Response, error)
	StopApp(context.Context, *AppControlRequest) (*Response, error)
	// ============================================================
	// App launch & placement (Layout, unified / JSON-less)
	//
	//	Launch apps and move/widen their windows across displays.
	//
	// ============================================================
	// LaunchApp — unified app launch (app.json or JSON-less) plus layout
	// (destName geometry, or initial_layout.json when destName is empty).
	LaunchApp(context.Context, *LaunchAppRequest) (*LaunchAppResponse, error)
	// LaunchApps — launch multiple apps simultaneously (best-effort)
	LaunchApps(context.Context, *LaunchAppsRequest) (*LaunchAppsResponse, error)
	// MoveWindow — JSON-less window move using virtual_display_areas
	MoveWindow(context.Context, *MoveWindowRequest) (*MoveWindowResponse, error)
	// MoveWindows — move multiple app windows simultaneously
	MoveWindows(context.Context, *MoveWindowsRequest) (*MoveWindowsResponse, error)
	// WidenApp — JSON-less app widen across two adjacent virtual displays
	WidenApp(context.Context, *WidenAppRequest) (*WidenAppResponse, error)
	// ListDestinations — enumerate all valid dest_name values (all 3 tiers)
	ListDestinations(context.Context, *ListDestinationsRequest) (*ListDestinationsResponse, error)
	// ============================================================
	// App mirroring (Layout)
	//
	//	Mirror a running app to another destination and remove it.
	//
	// ============================================================
	// CreateAppMirror — dynamically mirror a running app to another destination
	CreateAppMirror(context.Context, *CreateAppMirrorRequest) (*CreateAppMirrorResponse, error)
	// RemoveAppMirror — remove a previously created mirror layer
	RemoveAppMirror(context.Context, *RemoveAppMirrorRequest) (*RemoveAppMirrorResponse, error)
	// ============================================================
	// System layout & animation (Layout)
	//
	//	Apply system-wide layouts and run window animations.
	//
	// ============================================================
	ApplySystemLayout(context.Context, *Empty) (*Response, error)
	SetApplicationLayout(context.Context, *SetApplicationLayoutRequest) (*Response, error)
	// ReSyncSystemLayout — nudge every worker/compositor to catch up with the
	// master's cached scene without sending any layout change; a compositor
	// that was disconnected and reconnected receives its replay snapshot.
	ReSyncSystemLayout(context.Context, *Empty) (*Response, error)
	SetLayoutCommand(context.Context, *SetLayoutCommandRequest) (*Response, error)
	StartSystemAnimation(context.Context, *StartSystemAnimationRequest) (*Response, error)
	StartSystemAnimationAsync(context.Context, *StartSystemAnimationAsyncRequest) (*Response, error)
	WaitAsyncAnimation(context.Context, *WaitAsyncAnimationRequest) (*Response, error)
	WaitAllAsyncAnimations(context.Context, *Empty) (*Response, error)
	GetAnimationInfo(context.Context, *GetAnimationInfoRequest) (*GetAnimationInfoResponse, error)
	// ============================================================
	// Window activation & priority groups (Layout)
	// ============================================================
	// ActivateWindow — bring app layers to the front of their priority group
	ActivateWindow(context.Context, *ActivateWindowRequest) (*Response, error)
	// DeactivateWindow — send app layers to the back of their priority group and hide them
	DeactivateWindow(context.Context, *DeactivateWindowRequest) (*Response, error)
	// SetAppPriorityGroup — permanently reassign all layers of an app to the specified priority group
	SetAppPriorityGroup(context.Context, *SetAppPriorityGroupRequest) (*Response, error)
	// ListPriorityGroups — list all priority groups with their current runtime app assignments
	ListPriorityGroups(context.Context, *Empty) (*ListPriorityGroupsResponse, error)
	// ============================================================
	// Notifications (Layout)
	// ============================================================
	SubscribeNotifications(*Empty, UHMIService_SubscribeNotificationsServer) error
	mustEmbedUnimplementedUHMIServiceServer()
}

// UnimplementedUHMIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUHMIServiceServer struct {
}

func (UnimplementedUHMIServiceServer) StartAll(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAll not implemented")
}
func (UnimplementedUHMIServiceServer) StopAll(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAll not implemented")
}
func (UnimplementedUHMIServiceServer) ReloadConfig(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedUHMIServiceServer) ListAvailableApps(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableApps not implemented")
}
func (UnimplementedUHMIServiceServer) ListRunningApps(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunningApps not implemented")
}
func (UnimplementedUHMIServiceServer) GetAppCommand(context.Context, *AppControlRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppCommand not implemented")
}
func (UnimplementedUHMIServiceServer) GetAppStatus(context.Context, *AppControlRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppStatus not implemented")
}
func (UnimplementedUHMIServiceServer) RunAppCommand(context.Context, *AppCommandRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAppCommand not implemented")
}
func (UnimplementedUHMIServiceServer) RunApp(context.Context, *AppControlRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunApp not implemented")
}
func (UnimplementedUHMIServiceServer) RunAppAsync(context.Context, *AppControlRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunAppAsync not implemented")
}
func (UnimplementedUHMIServiceServer) StopApp(context.Context, *AppControlRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopApp not implemented")
}
func (UnimplementedUHMIServiceServer) LaunchApp(context.Context, *LaunchAppRequest) (*LaunchAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchApp not implemented")
}
func (UnimplementedUHMIServiceServer) LaunchApps(context.Context, *LaunchAppsRequest) (*LaunchAppsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchApps not implemented")
}
func (UnimplementedUHMIServiceServer) MoveWindow(context.Context, *MoveWindowRequest) (*MoveWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveWindow not implemented")
}
func (UnimplementedUHMIServiceServer) MoveWindows(context.Context, *MoveWindowsRequest) (*MoveWindowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveWindows not implemented")
}
func (UnimplementedUHMIServiceServer) WidenApp(context.Context, *WidenAppRequest) (*WidenAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WidenApp not implemented")
}
func (UnimplementedUHMIServiceServer) ListDestinations(context.Context, *ListDestinationsRequest) (*ListDestinationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDestinations not implemented")
}
func (UnimplementedUHMIServiceServer) CreateAppMirror(context.Context, *CreateAppMirrorRequest) (*CreateAppMirrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppMirror not implemented")
}
func (UnimplementedUHMIServiceServer) RemoveAppMirror(context.Context, *RemoveAppMirrorRequest) (*RemoveAppMirrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAppMirror not implemented")
}
func (UnimplementedUHMIServiceServer) ApplySystemLayout(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplySystemLayout not implemented")
}
func (UnimplementedUHMIServiceServer) SetApplicationLayout(context.Context, *SetApplicationLayoutRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetApplicationLayout not implemented")
}
func (UnimplementedUHMIServiceServer) ReSyncSystemLayout(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReSyncSystemLayout not implemented")
}
func (UnimplementedUHMIServiceServer) SetLayoutCommand(context.Context, *SetLayoutCommandRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLayoutCommand not implemented")
}
func (UnimplementedUHMIServiceServer) StartSystemAnimation(context.Context, *StartSystemAnimationRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSystemAnimation not implemented")
}
func (UnimplementedUHMIServiceServer) StartSystemAnimationAsync(context.Context, *StartSystemAnimationAsyncRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSystemAnimationAsync not implemented")
}
func (UnimplementedUHMIServiceServer) WaitAsyncAnimation(context.Context, *WaitAsyncAnimationRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitAsyncAnimation not implemented")
}
func (UnimplementedUHMIServiceServer) WaitAllAsyncAnimations(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitAllAsyncAnimations not implemented")
}
func (UnimplementedUHMIServiceServer) GetAnimationInfo(context.Context, *GetAnimationInfoRequest) (*GetAnimationInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimationInfo not implemented")
}
func (UnimplementedUHMIServiceServer) ActivateWindow(context.Context, *ActivateWindowRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateWindow not implemented")
}
func (UnimplementedUHMIServiceServer) DeactivateWindow(context.Context, *DeactivateWindowRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateWindow not implemented")
}
func (UnimplementedUHMIServiceServer) SetAppPriorityGroup(context.Context, *SetAppPriorityGroupRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAppPriorityGroup not implemented")
}
func (UnimplementedUHMIServiceServer) ListPriorityGroups(context.Context, *Empty) (*ListPriorityGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPriorityGroups not implemented")
}
func (UnimplementedUHMIServiceServer) SubscribeNotifications(*Empty, UHMIService_SubscribeNotificationsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeNotifications not implemented")
}
func (UnimplementedUHMIServiceServer) mustEmbedUnimplementedUHMIServiceServer() {}

// UnsafeUHMIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UHMIServiceServer will
// result in compilation errors.
type UnsafeUHMIServiceServer interface {
	mustEmbedUnimplementedUHMIServiceServer()
}

func RegisterUHMIServiceServer(s grpc.ServiceRegistrar, srv UHMIServiceServer) {
	s.RegisterService(&UHMIService_ServiceDesc, srv)
}

func _UHMIService_StartAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).StartAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_StartAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).StartAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_StopAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).StopAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_StopAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).StopAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ReloadConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ListAvailableApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ListAvailableApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ListAvailableApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ListAvailableApps(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ListRunningApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ListRunningApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ListRunningApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ListRunningApps(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_GetAppCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).GetAppCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_GetAppCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).GetAppCommand(ctx, req.(*AppControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_GetAppStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).GetAppStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_GetAppStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).GetAppStatus(ctx, req.(*AppControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_RunAppCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).RunAppCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_RunAppCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).RunAppCommand(ctx, req.(*AppCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_RunApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).RunApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_RunApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).RunApp(ctx, req.(*AppControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_RunAppAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).RunAppAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_RunAppAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).RunAppAsync(ctx, req.(*AppControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_StopApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).StopApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_StopApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).StopApp(ctx, req.(*AppControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_LaunchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).LaunchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_LaunchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).LaunchApp(ctx, req.(*LaunchAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_LaunchApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).LaunchApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_LaunchApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).LaunchApps(ctx, req.(*LaunchAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_MoveWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).MoveWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_MoveWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).MoveWindow(ctx, req.(*MoveWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_MoveWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveWindowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).MoveWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_MoveWindows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).MoveWindows(ctx, req.(*MoveWindowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_WidenApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidenAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).WidenApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_WidenApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).WidenApp(ctx, req.(*WidenAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ListDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDestinationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ListDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ListDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ListDestinations(ctx, req.(*ListDestinationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_CreateAppMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppMirrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).CreateAppMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_CreateAppMirror_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).CreateAppMirror(ctx, req.(*CreateAppMirrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_RemoveAppMirror_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAppMirrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).RemoveAppMirror(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_RemoveAppMirror_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).RemoveAppMirror(ctx, req.(*RemoveAppMirrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ApplySystemLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ApplySystemLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ApplySystemLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ApplySystemLayout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_SetApplicationLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetApplicationLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).SetApplicationLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_SetApplicationLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).SetApplicationLayout(ctx, req.(*SetApplicationLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ReSyncSystemLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ReSyncSystemLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ReSyncSystemLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ReSyncSystemLayout(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_SetLayoutCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLayoutCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).SetLayoutCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_SetLayoutCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).SetLayoutCommand(ctx, req.(*SetLayoutCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_StartSystemAnimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSystemAnimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).StartSystemAnimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_StartSystemAnimation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).StartSystemAnimation(ctx, req.(*StartSystemAnimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_StartSystemAnimationAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSystemAnimationAsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).StartSystemAnimationAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_StartSystemAnimationAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).StartSystemAnimationAsync(ctx, req.(*StartSystemAnimationAsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_WaitAsyncAnimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitAsyncAnimationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).WaitAsyncAnimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_WaitAsyncAnimation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).WaitAsyncAnimation(ctx, req.(*WaitAsyncAnimationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_WaitAllAsyncAnimations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).WaitAllAsyncAnimations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_WaitAllAsyncAnimations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).WaitAllAsyncAnimations(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_GetAnimationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).GetAnimationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_GetAnimationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).GetAnimationInfo(ctx, req.(*GetAnimationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ActivateWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ActivateWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ActivateWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ActivateWindow(ctx, req.(*ActivateWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_DeactivateWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).DeactivateWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_DeactivateWindow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).DeactivateWindow(ctx, req.(*DeactivateWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_SetAppPriorityGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAppPriorityGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).SetAppPriorityGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_SetAppPriorityGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).SetAppPriorityGroup(ctx, req.(*SetAppPriorityGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_ListPriorityGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UHMIServiceServer).ListPriorityGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UHMIService_ListPriorityGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UHMIServiceServer).ListPriorityGroups(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UHMIService_SubscribeNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UHMIServiceServer).SubscribeNotifications(m, &uHMIServiceSubscribeNotificationsServer{stream})
}

type UHMIService_SubscribeNotificationsServer interface {
	Send(*Notification) error
	grpc.ServerStream
}

type uHMIServiceSubscribeNotificationsServer struct {
	grpc.ServerStream
}

func (x *uHMIServiceSubscribeNotificationsServer) Send(m *Notification) error {
	return x.ServerStream.SendMsg(m)
}

// UHMIService_ServiceDesc is the grpc.ServiceDesc for UHMIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UHMIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uhmi.UHMIService",
	HandlerType: (*UHMIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartAll",
			Handler:    _UHMIService_StartAll_Handler,
		},
		{
			MethodName: "StopAll",
			Handler:    _UHMIService_StopAll_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _UHMIService_ReloadConfig_Handler,
		},
		{
			MethodName: "ListAvailableApps",
			Handler:    _UHMIService_ListAvailableApps_Handler,
		},
		{
			MethodName: "ListRunningApps",
			Handler:    _UHMIService_ListRunningApps_Handler,
		},
		{
			MethodName: "GetAppCommand",
			Handler:    _UHMIService_GetAppCommand_Handler,
		},
		{
			MethodName: "GetAppStatus",
			Handler:    _UHMIService_GetAppStatus_Handler,
		},
		{
			MethodName: "RunAppCommand",
			Handler:    _UHMIService_RunAppCommand_Handler,
		},
		{
			MethodName: "RunApp",
			Handler:    _UHMIService_RunApp_Handler,
		},
		{
			MethodName: "RunAppAsync",
			Handler:    _UHMIService_RunAppAsync_Handler,
		},
		{
			MethodName: "StopApp",
			Handler:    _UHMIService_StopApp_Handler,
		},
		{
			MethodName: "LaunchApp",
			Handler:    _UHMIService_LaunchApp_Handler,
		},
		{
			MethodName: "LaunchApps",
			Handler:    _UHMIService_LaunchApps_Handler,
		},
		{
			MethodName: "MoveWindow",
			Handler:    _UHMIService_MoveWindow_Handler,
		},
		{
			MethodName: "MoveWindows",
			Handler:    _UHMIService_MoveWindows_Handler,
		},
		{
			MethodName: "WidenApp",
			Handler:    _UHMIService_WidenApp_Handler,
		},
		{
			MethodName: "ListDestinations",
			Handler:    _UHMIService_ListDestinations_Handler,
		},
		{
			MethodName: "CreateAppMirror",
			Handler:    _UHMIService_CreateAppMirror_Handler,
		},
		{
			MethodName: "RemoveAppMirror",
			Handler:    _UHMIService_RemoveAppMirror_Handler,
		},
		{
			MethodName: "ApplySystemLayout",
			Handler:    _UHMIService_ApplySystemLayout_Handler,
		},
		{
			MethodName: "SetApplicationLayout",
			Handler:    _UHMIService_SetApplicationLayout_Handler,
		},
		{
			MethodName: "ReSyncSystemLayout",
			Handler:    _UHMIService_ReSyncSystemLayout_Handler,
		},
		{
			MethodName: "SetLayoutCommand",
			Handler:    _UHMIService_SetLayoutCommand_Handler,
		},
		{
			MethodName: "StartSystemAnimation",
			Handler:    _UHMIService_StartSystemAnimation_Handler,
		},
		{
			MethodName: "StartSystemAnimationAsync",
			Handler:    _UHMIService_StartSystemAnimationAsync_Handler,
		},
		{
			MethodName: "WaitAsyncAnimation",
			Handler:    _UHMIService_WaitAsyncAnimation_Handler,
		},
		{
			MethodName: "WaitAllAsyncAnimations",
			Handler:    _UHMIService_WaitAllAsyncAnimations_Handler,
		},
		{
			MethodName: "GetAnimationInfo",
			Handler:    _UHMIService_GetAnimationInfo_Handler,
		},
		{
			MethodName: "ActivateWindow",
			Handler:    _UHMIService_ActivateWindow_Handler,
		},
		{
			MethodName: "DeactivateWindow",
			Handler:    _UHMIService_DeactivateWindow_Handler,
		},
		{
			MethodName: "SetAppPriorityGroup",
			Handler:    _UHMIService_SetAppPriorityGroup_Handler,
		},
		{
			MethodName: "ListPriorityGroups",
			Handler:    _UHMIService_ListPriorityGroups_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeNotifications",
			Handler:       _UHMIService_SubscribeNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/uhmi.proto",
}
